"""sso connections

Revision ID: 1adba2d08ffa
Revises: 8f5a3465f640
Create Date: 2026-08-29 21:05:21.303989
"""

from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '1adba2d08ffa'
down_revision: str | None = '8f5a3465f640'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sso_connections',
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('protocol', sa.Enum('oidc', 'saml', name='ssoprotocol', native_enum=False, length=48), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('enforced', sa.Boolean(), nullable=False),
    sa.Column('domains', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('default_role', sa.Enum('owner', 'admin', 'security_admin', 'security_analyst', 'developer', 'auditor', 'billing_admin', name='membershiprole', native_enum=False, length=48), nullable=False),
    sa.Column('config', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_sso_connections_organization_id_organizations'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sso_connections')),
    sa.UniqueConstraint('organization_id', 'name', name=op.f('uq_sso_connections_organization_id_name'))
    )
    op.create_index(op.f('ix_sso_connections_organization_id'), 'sso_connections', ['organization_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sso_connections_organization_id'), table_name='sso_connections')
    op.drop_table('sso_connections')
    # ### end Alembic commands ###
