"""org region enum

Revision ID: 89d72fc74981
Revises: d7dd2cdb788f
Create Date: 2026-08-29 23:16:27.393661
"""

from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '89d72fc74981'
down_revision: str | None = 'd7dd2cdb788f'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('organizations', 'region',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.Enum('us', 'eu', 'me', 'apac', name='region', native_enum=False, length=48),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('organizations', 'region',
               existing_type=sa.Enum('us', 'eu', 'me', 'apac', name='region', native_enum=False, length=48),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False)
    # ### end Alembic commands ###
