"""behavior profiles

Revision ID: 8f5a3465f640
Revises: 40f038da955b
Create Date: 2026-08-29 19:44:55.966150
"""

from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '8f5a3465f640'
down_revision: str | None = '40f038da955b'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('behavior_profiles',
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('agent_id', sa.Uuid(), nullable=False),
    sa.Column('total_calls', sa.BigInteger(), nullable=False),
    sa.Column('tool_counts', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('tool_max_volume', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('destinations', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('classifications', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('recent_sequence', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('last_anomaly_score', sa.Integer(), nullable=False),
    sa.Column('last_evaluated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('baseline_since', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], name=op.f('fk_behavior_profiles_agent_id_agents'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_behavior_profiles_organization_id_organizations'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_behavior_profiles')),
    sa.UniqueConstraint('agent_id', name=op.f('uq_behavior_profiles_agent_id'))
    )
    op.create_index(op.f('ix_behavior_profiles_organization_id'), 'behavior_profiles', ['organization_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_behavior_profiles_organization_id'), table_name='behavior_profiles')
    op.drop_table('behavior_profiles')
    # ### end Alembic commands ###
