"""scim provisioning

Revision ID: fad64b1fdf15
Revises: 1adba2d08ffa
Create Date: 2026-08-29 21:26:23.903788
"""

from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = 'fad64b1fdf15'
down_revision: str | None = '1adba2d08ffa'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('scim_configs',
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=True),
    sa.Column('default_role', sa.Enum('owner', 'admin', 'security_admin', 'security_analyst', 'developer', 'auditor', 'billing_admin', name='membershiprole', native_enum=False, length=48), nullable=False),
    sa.Column('last_request_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_scim_configs_organization_id_organizations'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_scim_configs')),
    sa.UniqueConstraint('organization_id', name=op.f('uq_scim_configs_organization_id'))
    )
    op.create_index(op.f('ix_scim_configs_organization_id'), 'scim_configs', ['organization_id'], unique=False)
    op.create_table('scim_groups',
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('display_name', sa.String(length=255), nullable=False),
    sa.Column('external_id', sa.String(length=255), nullable=True),
    sa.Column('mapped_role', sa.Enum('owner', 'admin', 'security_admin', 'security_analyst', 'developer', 'auditor', 'billing_admin', name='membershiprole', native_enum=False, length=48), nullable=True),
    sa.Column('raw', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_scim_groups_organization_id_organizations'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_scim_groups')),
    sa.UniqueConstraint('organization_id', 'display_name', name=op.f('uq_scim_groups_organization_id_display_name'))
    )
    op.create_index(op.f('ix_scim_groups_external_id'), 'scim_groups', ['external_id'], unique=False)
    op.create_index(op.f('ix_scim_groups_organization_id'), 'scim_groups', ['organization_id'], unique=False)
    op.create_table('scim_users',
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('external_id', sa.String(length=255), nullable=True),
    sa.Column('user_name', sa.String(length=320), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('raw', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('deprovisioned_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_scim_users_organization_id_organizations'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_scim_users_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_scim_users')),
    sa.UniqueConstraint('organization_id', 'user_id', name=op.f('uq_scim_users_organization_id_user_id')),
    sa.UniqueConstraint('organization_id', 'user_name', name=op.f('uq_scim_users_organization_id_user_name'))
    )
    op.create_index(op.f('ix_scim_users_external_id'), 'scim_users', ['external_id'], unique=False)
    op.create_index(op.f('ix_scim_users_organization_id'), 'scim_users', ['organization_id'], unique=False)
    op.create_index(op.f('ix_scim_users_user_id'), 'scim_users', ['user_id'], unique=False)
    op.create_table('scim_group_members',
    sa.Column('group_id', sa.Uuid(), nullable=False),
    sa.Column('scim_user_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['scim_groups.id'], name=op.f('fk_scim_group_members_group_id_scim_groups'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['scim_user_id'], ['scim_users.id'], name=op.f('fk_scim_group_members_scim_user_id_scim_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('group_id', 'scim_user_id', name=op.f('pk_scim_group_members'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('scim_group_members')
    op.drop_index(op.f('ix_scim_users_user_id'), table_name='scim_users')
    op.drop_index(op.f('ix_scim_users_organization_id'), table_name='scim_users')
    op.drop_index(op.f('ix_scim_users_external_id'), table_name='scim_users')
    op.drop_table('scim_users')
    op.drop_index(op.f('ix_scim_groups_organization_id'), table_name='scim_groups')
    op.drop_index(op.f('ix_scim_groups_external_id'), table_name='scim_groups')
    op.drop_table('scim_groups')
    op.drop_index(op.f('ix_scim_configs_organization_id'), table_name='scim_configs')
    op.drop_table('scim_configs')
    # ### end Alembic commands ###
